services:
  backend:
    container_name: be
    image: ghcr.io/buraito-kun/test-mono-repo/backend
    pull_policy: if_not_present
    restart: always
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3001"
  frontend:
    container_name: fe
    image: ghcr.io/buraito-kun/test-mono-repo/frontend
    pull_policy: if_not_present
    restart: always
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:3000"
