services:
  backend:
    container_name: be
    image: ghcr.io/buraito-kun/test-mono-repo/backend
    pull_policy: if_not_present
    restart: always
    ports:
      - "3001:3001"
  frontend:
    container_name: fe
    image: ghcr.io/buraito-kun/test-mono-repo/frontend
    pull_policy: if_not_present
    restart: always
    ports:
      - "3000:3000"
