name: Release Semantic Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: use release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/test-mono-repo/frontend:latest ./apps/frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/test-mono-repo/backend:latest ./apps/backend
          docker push ghcr.io/${{ github.repository_owner }}/test-mono-repo/frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/test-mono-repo/backend:latest
